"""removed category class

Revision ID: 38bc5c6eec74
Revises: e316a9de463c
Create Date: 2018-09-12 08:19:47.140637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bc5c6eec74'
down_revision = 'e316a9de463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category')
    op.add_column('pitch', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_category_id_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'comment', ['comment_id'], ['id'])
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_category_id_fkey', 'pitch', 'category', ['category_id'], ['id'])
    op.drop_column('pitch', 'comment_id')
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
